"""
PostgreSQL database abstraction layer for paper-scanner.

Handles:
- Connection management with context managers
- Paper model to SQL row conversion
- Bulk insert/upsert operations with conflict handling
- Transaction management
- DOI and cite_key deduplication logic
"""

import json
import logging
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import psycopg2
from psycopg2 import sql
from psycopg2.extras import Json, RealDictCursor
from psycopg2.pool import SimpleConnectionPool

from paper_scanner.core.models import Paper

logger = logging.getLogger(__name__)


class DatabaseConnectionPool:
    """Manages PostgreSQL connection pooling"""

    def __init__(
        self,
        database_url: str,
        min_connections: int = 1,
        max_connections: int = 5,
    ):
        """
        Initialize connection pool.
        
        Args:
            database_url: PostgreSQL connection string (postgresql://user:pass@host:port/db)
            min_connections: Minimum pool size
            max_connections: Maximum pool size
        """
        self.database_url = database_url
        self._pool: Optional[SimpleConnectionPool] = None
        self.min_connections = min_connections
        self.max_connections = max_connections

    def initialize(self) -> None:
        """Create connection pool"""
        if self._pool is None:
            try:
                self._pool = SimpleConnectionPool(
                    self.min_connections,
                    self.max_connections,
                    self.database_url,
                )
                logger.info(f"Connection pool initialized: {self.min_connections}-{self.max_connections} connections")
            except psycopg2.Error as e:
                logger.error(f"Failed to initialize connection pool: {e}")
                raise

    def close(self) -> None:
        """Close all connections in pool"""
        if self._pool is not None:
            self._pool.closeall()
            self._pool = None
            logger.info("Connection pool closed")

    @contextmanager
    def get_connection(self):
        """Get connection from pool with context manager"""
        if self._pool is None:
            raise RuntimeError("Connection pool not initialized. Call initialize() first.")

        conn = self._pool.getconn()
        try:
            yield conn
        except Exception as e:
            conn.rollback()
            logger.error(f"Database connection error: {e}")
            raise
        finally:
            self._pool.putconn(conn)


class PaperToRowConverter:
    """Converts Pydantic Paper model to SQL row format"""

    @staticmethod
    def paper_to_row(paper: Paper) -> Dict[str, Any]:
        """
        Convert Paper model to PostgreSQL row dictionary.
        
        Maps Paper model fields to papers table columns:
        - id (UUID) → stored as VARCHAR
        - db_id (auto-increment) → generated by DB
        - cite_key → stored as UNIQUE VARCHAR
        - doi, source_key → stored as-is
        - keywords, topics → stored as JSONB arrays
        - authors → stored as JSONB with full Author objects
        - abstract → stored as TEXT
        - discovery → stored as JSONB
        - screening → stored as JSONB
        - pdf_info → stored as JSONB
        
        Args:
            paper: Paper model instance
            
        Returns:
            Dictionary with SQL column names and serialized values
        """
        # Serialize complex fields to JSON
        authors_json = [author.model_dump(mode='json', exclude_none=True) for author in paper.authors] if paper.authors else []
        discovery_json = paper.discovery.model_dump(mode='json', exclude_none=True) if paper.discovery else None
        screening_json = paper.screening.model_dump(mode='json', exclude_none=True) if paper.screening else None
        conceptual_analysis_json = (
            paper.conceptual_analysis.model_dump(mode='json', exclude_none=True)
            if paper.conceptual_analysis else None
        )

        # Build row dictionary
        row = {
            'id': paper.id,  # UUID as VARCHAR
            'cite_key': paper.cite_key,
            'source_key': paper.source_key,
            'title': paper.title,
            'abstract': paper.abstract,
            'authors': Json(authors_json),
            'keywords': paper.keywords or [],
            'topics': paper.topics or [],
            'year': paper.year,
            'journal': paper.journal,
            'journal_abbreviation': paper.journal_abbreviation,
            'booktitle': paper.booktitle,
            'publisher': paper.publisher,
            'volume': paper.volume,
            'issue': paper.number,  # maps to 'issue' in SQL
            'pages': paper.pages,
            'paper_type': paper.paper_type.value if paper.paper_type else None,
            'doi': paper.doi,
            'arxiv_id': paper.arxiv_id,
            'pmid': paper.pmid,
            'isbn': paper.isbn,
            'issn': paper.issn,
            'url': paper.url,
            'language': paper.language,
            'created_at': paper.created_at,
            'updated_at': paper.updated_at,
            'manually_validated': paper.manually_validated,
            'validation_notes': paper.validation_notes,
            'validated_by': paper.validated_by,
            'validated_at': paper.validated_at,
            'discovery': Json(discovery_json),
            'screening': Json(screening_json),
            'conceptual_analysis': Json(conceptual_analysis_json),
            'raw_bibtex': paper.raw_bibtex,
            'raw_json': Json(paper.raw_json) if paper.raw_json else None,
        }

        if paper.pdf_info:
            row['pdf_info'] = Json(paper.pdf_info.model_dump(mode='json', exclude_none=True))
            row['file_path'] = paper.pdf_info.file_path
            row['file_name'] = paper.pdf_info.file_name
            row['size_bytes'] = paper.pdf_info.file_size_bytes
            row['created_time'] = paper.pdf_info.downloaded_at


        return row

    @staticmethod
    def row_to_paper(row: Dict[str, Any]) -> Paper:
        """
        Convert PostgreSQL row to Paper model.
        
        Reverses paper_to_row() conversion.
        
        Args:
            row: Dictionary from database query
            
        Returns:
            Paper model instance
        """
        from paper_scanner.core.models import Author, Discovery, PDFInfo, Screening

        # Deserialize authors from JSONB
        authors = []
        if row.get('authors'):
            for author_dict in row['authors']:
                try:
                    authors.append(Author(**author_dict))
                except Exception as e:
                    logger.warning(f"Failed to deserialize author: {e}")

        # Deserialize complex fields from JSONB
        discovery = None
        if row.get('discovery'):
            try:
                discovery = Discovery(**row['discovery'])
            except Exception as e:
                logger.warning(f"Failed to deserialize discovery: {e}")

        screening = None
        if row.get('screening'):
            try:
                screening = Screening(**row['screening'])
            except Exception as e:
                logger.warning(f"Failed to deserialize screening: {e}")

        pdf_info = None
        if row.get('pdf_info'):
            try:
                pdf_info = PDFInfo(**row['pdf_info'])
            except Exception as e:
                logger.warning(f"Failed to deserialize pdf_info: {e}")

        # Create Paper instance
        paper = Paper(
            id=row.get('id'),
            db_id=row.get('db_id'),
            cite_key=row['cite_key'],
            source_key=row.get('source_key'),
            title=row.get('title'),
            abstract=row.get('abstract'),
            authors=authors,
            keywords=row.get('keywords') or [],
            topics=row.get('topics') or [],
            year=row.get('year'),
            journal=row.get('journal'),
            journal_abbreviation=row.get('journal_abbreviation'),
            booktitle=row.get('booktitle'),
            publisher=row.get('publisher'),
            volume=row.get('volume'),
            number=row.get('issue'),
            pages=row.get('pages'),
            paper_type=row.get('paper_type'),
            doi=row.get('doi'),
            arxiv_id=row.get('arxiv_id'),
            pmid=row.get('pmid'),
            isbn=row.get('isbn'),
            issn=row.get('issn'),
            url=row.get('url'),
            language=row.get('language'),
            created_at=row.get('created_at'),
            updated_at=row.get('updated_at'),
            manually_validated=row.get('manually_validated', False),
            validation_notes=row.get('validation_notes'),
            validated_by=row.get('validated_by'),
            validated_at=row.get('validated_at'),
            discovery=discovery,
            screening=screening,
            pdf_info=pdf_info,
            raw_bibtex=row.get('raw_bibtex'),
            raw_json=row.get('raw_json'),
        )

        return paper


class PaperUploader:
    """Handles bulk paper uploads with conflict resolution"""

    def __init__(self, pool: DatabaseConnectionPool):
        """
        Initialize uploader with connection pool.
        
        Args:
            pool: DatabaseConnectionPool instance
        """
        self.pool = pool

    @contextmanager
    def transaction(self, conn):
        """Context manager for transactions"""
        try:
            yield conn
            conn.commit()
        except Exception as e:
            conn.rollback()
            logger.error(f"Transaction rolled back: {e}")
            raise

    def insert_papers(
        self,
        papers: List[Paper],
        conflict_strategy: str = "skip",
        dry_run: bool = False,
    ) -> Dict[str, Any]:
        """
        Insert papers into database with conflict handling.
        
        Args:
            papers: List of Paper models to insert
            conflict_strategy: How to handle conflicts
                - "skip": Skip papers with duplicate cite_key
                - "update": Update existing papers with same cite_key
                - "raise": Raise error on conflict
            dry_run: If True, don't actually insert
            
        Returns:
            Dictionary with insertion statistics:
            {
                "inserted": int,
                "updated": int,
                "skipped": int,
                "errors": List[str],
                "error_count": int,
                "citation_edges": {
                    "edges_inserted": int,
                    "edges_skipped": int,
                }
            }
        """
        stats = {
            "inserted": 0,
            "updated": 0,
            "skipped": 0,
            "errors": [],
            "error_count": 0,
            "citation_edges": {
                "edges_inserted": 0,
                "edges_skipped": 0,
            }
        }

        if not papers:
            logger.info("No papers to insert")
            return stats

        if dry_run:
            logger.info(f"DRY RUN: Would insert {len(papers)} papers")
            return {"inserted": len(papers), **{k: v for k, v in stats.items() if k != "inserted"}}

        try:
            with self.pool.get_connection() as conn:
                with self.transaction(conn):
                    cursor = conn.cursor()

                    for paper in papers:
                        try:
                            self._insert_single_paper(cursor, paper, conflict_strategy)
                            stats["inserted"] += 1
                        except Exception as e:
                            error_msg = f"Paper {paper.cite_key}: {str(e)}"
                            logger.error(error_msg)
                            stats["errors"].append(error_msg)
                            stats["error_count"] += 1

                            if conflict_strategy == "raise":
                                raise

                    # Insert citation edges after all papers
                    edge_stats = self._insert_citation_edges(cursor, papers)
                    stats["citation_edges"]["edges_inserted"] = edge_stats["edges_inserted"]
                    stats["citation_edges"]["edges_skipped"] = edge_stats["edges_skipped"]
                    if edge_stats["errors"]:
                        stats["errors"].extend(edge_stats["errors"])

                    cursor.close()
                    logger.info(
                        f"Inserted {stats['inserted']} papers, {stats['citation_edges']['edges_inserted']} "
                        f"citation edges, errors: {stats['error_count']}"
                    )

        except Exception as e:
            logger.error(f"Bulk insert failed: {e}")
            raise

        return stats

    def _insert_single_paper(
        self,
        cursor,
        paper: Paper,
        conflict_strategy: str = "skip",
    ) -> None:
        """
        Insert or update a single paper.
        
        Args:
            cursor: psycopg2 cursor
            paper: Paper model
            conflict_strategy: How to handle conflicts
        """
        row = PaperToRowConverter.paper_to_row(paper)

        # Build INSERT ... ON CONFLICT query
        columns = list(row.keys())

        # Build the base INSERT statement
        values_placeholders = sql.SQL(', ').join(
            sql.Placeholder(name=col) for col in columns
        )

        insert_sql = sql.SQL(
            "INSERT INTO papers ({}) VALUES ({})"
        ).format(
            sql.SQL(', ').join(map(sql.Identifier, columns)),
            values_placeholders
        )

        # Add conflict handling clause
        if conflict_strategy == "skip":
            insert_sql += sql.SQL(" ON CONFLICT (cite_key) DO NOTHING")
        elif conflict_strategy == "update":
            # Update all fields except cite_key and db_id on conflict
            update_cols = [col for col in columns if col not in ("cite_key", "db_id")]
            update_clause = sql.SQL(', ').join(
                sql.SQL('{} = EXCLUDED.{}').format(sql.Identifier(col), sql.Identifier(col))
                for col in update_cols
            )
            insert_sql += sql.SQL(" ON CONFLICT (cite_key) DO UPDATE SET ") + update_clause

        cursor.execute(insert_sql, row)

    def _insert_citation_edges(
        self,
        cursor,
        papers: List[Paper],
    ) -> Dict[str, Any]:
        """
        Insert citation edges for all papers.
        
        For each paper with citations, creates edges linking the citing paper
        to cited papers. Handles cases where cited papers may or may not be in DB.
        
        Args:
            cursor: psycopg2 cursor (should be in transaction)
            papers: List of Paper models with citations
            
        Returns:
            Dictionary with edge insertion statistics:
            {
                "edges_inserted": int,
                "edges_skipped": int,  # cited paper not in DB
                "errors": List[str]
            }
        """
        stats = {
            "edges_inserted": 0,
            "edges_skipped": 0,
            "errors": [],
        }

        for paper in papers:
            if not paper.citations:
                continue
            
            # Get citing paper's db_id
            cursor.execute("SELECT db_id FROM papers WHERE id = %s", (paper.id,))
            result = cursor.fetchone()
            
            if not result:
                stats["errors"].append(f"Paper {paper.cite_key} not found in DB for citations")
                continue
            
            citing_paper_db_id = result[0]
            
            # Insert edges for each citation
            for citation in paper.citations:
                try:
                    cited_paper_db_id = None
                    
                    # Try to find the cited paper by DOI first, then by title+year
                    if citation.doi:
                        cursor.execute(
                            "SELECT db_id FROM papers WHERE doi = %s LIMIT 1",
                            (citation.doi,)
                        )
                        result = cursor.fetchone()
                        if result:
                            cited_paper_db_id = result[0]
                    
                    if not cited_paper_db_id and citation.title:
                        cursor.execute(
                            "SELECT db_id FROM papers WHERE title = %s AND year = %s LIMIT 1",
                            (citation.title, citation.year)
                        )
                        result = cursor.fetchone()
                        if result:
                            cited_paper_db_id = result[0]
                    
                    # Insert edge (cited_paper_db_id can be NULL if not found)
                    cursor.execute(
                        """
                        INSERT INTO citation_edges (citing_paper_id, cited_paper_id)
                        VALUES (%s, %s)
                        ON CONFLICT (citing_paper_id, cited_paper_id) DO NOTHING
                        """,
                        (citing_paper_db_id, cited_paper_db_id)
                    )
                    
                    if cited_paper_db_id is None:
                        stats["edges_skipped"] += 1
                    else:
                        stats["edges_inserted"] += 1
                        
                except Exception as e:
                    error_msg = f"Citation edge for {paper.cite_key}: {str(e)}"
                    logger.error(error_msg)
                    stats["errors"].append(error_msg)

        return stats

    def get_paper_by_cite_key(self, cite_key: str) -> Optional[Paper]:
        """
        Retrieve paper by cite_key.
        
        Args:
            cite_key: Citation key
            
        Returns:
            Paper model or None if not found
        """
        try:
            with self.pool.get_connection() as conn:
                cursor = conn.cursor(cursor_factory=RealDictCursor)
                cursor.execute(
                    "SELECT * FROM papers WHERE cite_key = %s",
                    (cite_key,)
                )
                row = cursor.fetchone()
                cursor.close()

                if row:
                    return PaperToRowConverter.row_to_paper(dict(row))
                return None

        except Exception as e:
            logger.error(f"Failed to get paper by cite_key: {e}")
            raise

    def get_papers_by_doi(self, doi: str) -> List[Paper]:
        """
        Retrieve papers by DOI (may be multiple for duplicates).
        
        Args:
            doi: DOI string
            
        Returns:
            List of Paper models
        """
        try:
            with self.pool.get_connection() as conn:
                cursor = conn.cursor(cursor_factory=RealDictCursor)
                cursor.execute(
                    "SELECT * FROM papers WHERE doi = %s",
                    (doi,)
                )
                rows = cursor.fetchall()
                cursor.close()

                return [PaperToRowConverter.row_to_paper(dict(row)) for row in rows]

        except Exception as e:
            logger.error(f"Failed to get papers by DOI: {e}")
            raise

    def count_papers(self) -> int:
        """Get total paper count in database"""
        try:
            with self.pool.get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT COUNT(*) FROM papers")
                count = cursor.fetchone()[0]
                cursor.close()
                return count

        except Exception as e:
            logger.error(f"Failed to count papers: {e}")
            raise


class DOIDuplicateHandler:
    """Handles DOI-based duplicate detection and management"""

    @staticmethod
    def normalize_doi(doi: Optional[str]) -> Optional[str]:
        """
        Normalize DOI for comparison.
        
        Removes leading/trailing spaces and converts to lowercase.
        
        Args:
            doi: DOI string
            
        Returns:
            Normalized DOI or None
        """
        if not doi:
            return None
        return doi.strip().lower()

    @staticmethod
    def mark_duplicate(
        cursor,
        duplicate_paper_id: str,
        primary_paper_id: str,
    ) -> None:
        """
        Mark a paper as duplicate of another.
        
        Updates duplicate_of field (stored as JSONB containing primary paper's ID).
        
        Args:
            cursor: psycopg2 cursor
            duplicate_paper_id: Paper to mark as duplicate
            primary_paper_id: Paper it's a duplicate of
        """
        duplicate_info = json.dumps({
            "id": primary_paper_id,
            "marked_at": datetime.now(timezone.utc).isoformat(),
        })

        cursor.execute(
            "UPDATE papers SET duplicate_of = %s WHERE id = %s",
            (Json(json.loads(duplicate_info)), duplicate_paper_id)
        )
